# Generated by Django 5.0.3 on 2024-05-18 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pdf_id_carrera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=50)),
                ('semestre', models.IntegerField()),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='core.carrera')),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pdf')),
            ],
        ),
    ]
