# Generated by Django 5.0.3 on 2024-05-19 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_programa_carrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='core.carrera'),
        ),
    ]
