# Generated by Django 5.0.3 on 2024-05-21 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_programa_carrera'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Programa',
        ),
    ]
